-- ========================================
-- SCRIPT DE INICIALIZACIÓN DE BASE DE DATOS
-- Sistema de Gestión de Laboratorios Clínicos
-- Oracle Database Express Edition (XE)
-- ========================================

-- Conectarse como SYSTEM
-- CONN system/Oracle123@XE

-- ========================================
-- 1. CREACIÓN DE USUARIO Y PERMISOS
-- ========================================

-- Crear usuario de aplicación
CREATE USER laboratorio_user IDENTIFIED BY Lab2025Pass
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Otorgar permisos
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO laboratorio_user;
GRANT CREATE SESSION TO laboratorio_user;
GRANT SELECT ANY TABLE TO laboratorio_user;

-- Conectarse con el nuevo usuario
ALTER SESSION SET CURRENT_SCHEMA = laboratorio_user;

-- ========================================
-- 2. ELIMINACIÓN DE OBJETOS EXISTENTES
-- ========================================

BEGIN
  FOR c IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS');
  END LOOP;
  
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE ('DROP SEQUENCE ' || s.sequence_name);
  END LOOP;
END;
/

-- ========================================
-- 3. CREACIÓN DE SECUENCIAS
-- ========================================

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LABORATORIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_ANALISIS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CITA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESULTADO START WITH 1 INCREMENT BY 1;

-- ========================================
-- 4. CREACIÓN DE TABLAS
-- ========================================

-- Tabla: ROLES
CREATE TABLE ROLES (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200),
    PERMISOS VARCHAR2(500),
    CONSTRAINT CHK_ROL_NOMBRE CHECK (NOMBRE IN ('ADMINISTRADOR', 'PACIENTE', 'LABORATORISTA', 'MEDICO'))
);

-- Tabla: USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(50) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO NUMBER(1) DEFAULT 1,
    CONSTRAINT CHK_USUARIO_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT CHK_USUARIO_ROL CHECK (ROL IN ('ADMINISTRADOR', 'PACIENTE', 'LABORATORISTA', 'MEDICO'))
);

-- Tabla: LABORATORIOS
CREATE TABLE LABORATORIOS (
    ID_LABORATORIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    DIRECCION VARCHAR2(300) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    ESPECIALIDAD VARCHAR2(100),
    ACTIVO NUMBER(1) DEFAULT 1,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_LAB_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UNQ_LAB_EMAIL UNIQUE (EMAIL)
);

-- Tabla: TIPOS_ANALISIS
CREATE TABLE TIPOS_ANALISIS (
    ID_TIPO_ANALISIS NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER(10,2) NOT NULL,
    TIEMPO_ENTREGA_DIAS NUMBER(3) NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 1,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_ANALISIS_PRECIO CHECK (PRECIO > 0),
    CONSTRAINT CHK_ANALISIS_TIEMPO CHECK (TIEMPO_ENTREGA_DIAS > 0),
    CONSTRAINT CHK_ANALISIS_ACTIVO CHECK (ACTIVO IN (0, 1))
);

-- Tabla: LABORATORIO_ANALISIS (Relación N:M)
CREATE TABLE LABORATORIO_ANALISIS (
    ID_LABORATORIO NUMBER NOT NULL,
    ID_TIPO_ANALISIS NUMBER NOT NULL,
    DISPONIBLE NUMBER(1) DEFAULT 1,
    FECHA_ASIGNACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_LABORATORIO, ID_TIPO_ANALISIS),
    CONSTRAINT FK_LA_LABORATORIO FOREIGN KEY (ID_LABORATORIO) REFERENCES LABORATORIOS(ID_LABORATORIO) ON DELETE CASCADE,
    CONSTRAINT FK_LA_TIPO_ANALISIS FOREIGN KEY (ID_TIPO_ANALISIS) REFERENCES TIPOS_ANALISIS(ID_TIPO_ANALISIS) ON DELETE CASCADE,
    CONSTRAINT CHK_LA_DISPONIBLE CHECK (DISPONIBLE IN (0, 1))
);

-- Tabla: CITAS
CREATE TABLE CITAS (
    ID_CITA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER NOT NULL,
    ID_LABORATORIO NUMBER NOT NULL,
    ID_TIPO_ANALISIS NUMBER NOT NULL,
    FECHA_CITA TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(50) DEFAULT 'PROGRAMADA',
    OBSERVACIONES VARCHAR2(500),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_CITA_LABORATORIO FOREIGN KEY (ID_LABORATORIO) REFERENCES LABORATORIOS(ID_LABORATORIO),
    CONSTRAINT FK_CITA_TIPO_ANALISIS FOREIGN KEY (ID_TIPO_ANALISIS) REFERENCES TIPOS_ANALISIS(ID_TIPO_ANALISIS),
    CONSTRAINT CHK_CITA_ESTADO CHECK (ESTADO IN ('PROGRAMADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA'))
);

-- Tabla: RESULTADOS_ANALISIS
CREATE TABLE RESULTADOS_ANALISIS (
    ID_RESULTADO NUMBER PRIMARY KEY,
    ID_CITA NUMBER NOT NULL,
    ID_LABORATORISTA NUMBER NOT NULL,
    ARCHIVO_PDF VARCHAR2(500),
    OBSERVACIONES VARCHAR2(1000),
    FECHA_RESULTADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR2(50) DEFAULT 'PENDIENTE',
    VALORES_MEDIDOS CLOB,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RESULTADO_CITA FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA) ON DELETE CASCADE,
    CONSTRAINT FK_RESULTADO_LABORATORISTA FOREIGN KEY (ID_LABORATORISTA) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CHK_RESULTADO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'REVISADO')),
    CONSTRAINT UNQ_RESULTADO_CITA UNIQUE (ID_CITA)
);

-- ========================================
-- 5. CREACIÓN DE ÍNDICES
-- ========================================

CREATE INDEX IDX_USUARIO_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIO_ROL ON USUARIOS(ROL);
CREATE INDEX IDX_CITA_PACIENTE ON CITAS(ID_PACIENTE);
CREATE INDEX IDX_CITA_LABORATORIO ON CITAS(ID_LABORATORIO);
CREATE INDEX IDX_CITA_FECHA ON CITAS(FECHA_CITA);
CREATE INDEX IDX_LAB_ACTIVO ON LABORATORIOS(ACTIVO);
CREATE INDEX IDX_RESULTADO_CITA ON RESULTADOS_ANALISIS(ID_CITA);
CREATE INDEX IDX_RESULTADO_LABORATORISTA ON RESULTADOS_ANALISIS(ID_LABORATORISTA);
CREATE INDEX IDX_RESULTADO_ESTADO ON RESULTADOS_ANALISIS(ESTADO);
CREATE INDEX IDX_RESULTADO_FECHA ON RESULTADOS_ANALISIS(FECHA_RESULTADO);

-- ========================================
-- 6. INSERCIÓN DE DATOS INICIALES
-- ========================================

-- Roles
INSERT INTO ROLES VALUES (SEQ_ROL.NEXTVAL, 'ADMINISTRADOR', 'Administrador del sistema con acceso completo', 'ALL');
INSERT INTO ROLES VALUES (SEQ_ROL.NEXTVAL, 'PACIENTE', 'Paciente que puede agendar citas y ver resultados', 'READ,CREATE_CITA');
INSERT INTO ROLES VALUES (SEQ_ROL.NEXTVAL, 'LABORATORISTA', 'Personal de laboratorio', 'READ,WRITE,UPDATE_RESULTADO');
INSERT INTO ROLES VALUES (SEQ_ROL.NEXTVAL, 'MEDICO', 'Médico que puede ver resultados de pacientes', 'READ,CREATE_CITA');

-- Usuarios (password es "password123" hasheado con BCrypt: $2a$10$1234567890...)
-- Nota: Las contraseñas serán hasheadas por la aplicación, aquí ponemos texto plano solo para inicialización
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, PASSWORD, ROL, ACTIVO) 
VALUES (SEQ_USUARIO.NEXTVAL, 'Admin', 'Sistema', 'admin@lab.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMINISTRADOR', 1);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, PASSWORD, ROL, ACTIVO) 
VALUES (SEQ_USUARIO.NEXTVAL, 'María', 'González', 'maria.gonzalez@email.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'PACIENTE', 1);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, PASSWORD, ROL, ACTIVO) 
VALUES (SEQ_USUARIO.NEXTVAL, 'Carlos', 'López', 'carlos.lopez@lab.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'LABORATORISTA', 1);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, PASSWORD, ROL, ACTIVO) 
VALUES (SEQ_USUARIO.NEXTVAL, 'Ana', 'Martínez', 'ana.martinez@hospital.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'MEDICO', 1);

INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, PASSWORD, ROL, ACTIVO) 
VALUES (SEQ_USUARIO.NEXTVAL, 'Pedro', 'Silva', 'pedro.silva@email.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'PACIENTE', 1);

-- Laboratorios (mínimo 3 requeridos)
INSERT INTO LABORATORIOS (ID_LABORATORIO, NOMBRE, DIRECCION, TELEFONO, EMAIL, ESPECIALIDAD, ACTIVO) 
VALUES (SEQ_LABORATORIO.NEXTVAL, 'Laboratorio Clínico Central', 'Av. Libertador Bernardo O''Higgins 1234, Santiago', '+56-2-2345-6789', 'contacto@labcentral.cl', 'Análisis General', 1);

INSERT INTO LABORATORIOS (ID_LABORATORIO, NOMBRE, DIRECCION, TELEFONO, EMAIL, ESPECIALIDAD, ACTIVO) 
VALUES (SEQ_LABORATORIO.NEXTVAL, 'Laboratorio de Análisis Especializados', 'Av. Providencia 2567, Providencia', '+56-2-2876-5432', 'info@labespecializado.cl', 'Análisis Especializados', 1);

INSERT INTO LABORATORIOS (ID_LABORATORIO, NOMBRE, DIRECCION, TELEFONO, EMAIL, ESPECIALIDAD, ACTIVO) 
VALUES (SEQ_LABORATORIO.NEXTVAL, 'Laboratorio de Diagnóstico Rápido', 'Av. Apoquindo 4500, Las Condes', '+56-2-2654-3210', 'atencion@labrapido.cl', 'Diagnóstico Rápido', 1);

INSERT INTO LABORATORIOS (ID_LABORATORIO, NOMBRE, DIRECCION, TELEFONO, EMAIL, ESPECIALIDAD, ACTIVO) 
VALUES (SEQ_LABORATORIO.NEXTVAL, 'Laboratorio Médico Integrado', 'Calle Las Tranqueras 567, Vitacura', '+56-2-2789-1234', 'contacto@labintegrado.cl', 'Medicina Integral', 1);

-- Tipos de Análisis
INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'Hemograma Completo', 'Análisis completo de células sanguíneas', 15000, 1, 1);

INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'Perfil Bioquímico', 'Glucosa, colesterol, triglicéridos, función hepática y renal', 25000, 2, 1);

INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'Examen de Orina Completo', 'Análisis físico, químico y microscópico de orina', 12000, 1, 1);

INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'Perfil Tiroideo', 'TSH, T3, T4 libre', 35000, 3, 1);

INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'PCR para COVID-19', 'Test PCR para detección de SARS-CoV-2', 30000, 1, 1);

INSERT INTO TIPOS_ANALISIS (ID_TIPO_ANALISIS, NOMBRE, DESCRIPCION, PRECIO, TIEMPO_ENTREGA_DIAS, ACTIVO) 
VALUES (SEQ_TIPO_ANALISIS.NEXTVAL, 'Perfil Lipídico', 'Colesterol total, HDL, LDL, triglicéridos', 20000, 2, 1);

-- Asignación de Análisis a Laboratorios
-- Laboratorio Central ofrece análisis generales
INSERT INTO LABORATORIO_ANALISIS VALUES (1, 1, 1, CURRENT_TIMESTAMP); -- Hemograma
INSERT INTO LABORATORIO_ANALISIS VALUES (1, 2, 1, CURRENT_TIMESTAMP); -- Perfil Bioquímico
INSERT INTO LABORATORIO_ANALISIS VALUES (1, 3, 1, CURRENT_TIMESTAMP); -- Orina
INSERT INTO LABORATORIO_ANALISIS VALUES (1, 6, 1, CURRENT_TIMESTAMP); -- Perfil Lipídico

-- Laboratorio Especializado
INSERT INTO LABORATORIO_ANALISIS VALUES (2, 2, 1, CURRENT_TIMESTAMP); -- Perfil Bioquímico
INSERT INTO LABORATORIO_ANALISIS VALUES (2, 4, 1, CURRENT_TIMESTAMP); -- Perfil Tiroideo
INSERT INTO LABORATORIO_ANALISIS VALUES (2, 6, 1, CURRENT_TIMESTAMP); -- Perfil Lipídico

-- Laboratorio Rápido
INSERT INTO LABORATORIO_ANALISIS VALUES (3, 1, 1, CURRENT_TIMESTAMP); -- Hemograma
INSERT INTO LABORATORIO_ANALISIS VALUES (3, 3, 1, CURRENT_TIMESTAMP); -- Orina
INSERT INTO LABORATORIO_ANALISIS VALUES (3, 5, 1, CURRENT_TIMESTAMP); -- PCR COVID

-- Laboratorio Integrado
INSERT INTO LABORATORIO_ANALISIS VALUES (4, 1, 1, CURRENT_TIMESTAMP); -- Hemograma
INSERT INTO LABORATORIO_ANALISIS VALUES (4, 2, 1, CURRENT_TIMESTAMP); -- Perfil Bioquímico
INSERT INTO LABORATORIO_ANALISIS VALUES (4, 4, 1, CURRENT_TIMESTAMP); -- Perfil Tiroideo
INSERT INTO LABORATORIO_ANALISIS VALUES (4, 5, 1, CURRENT_TIMESTAMP); -- PCR COVID

-- Citas de Ejemplo
INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 2, 1, 1, TIMESTAMP '2025-11-05 09:00:00', 'PROGRAMADA', 'Ayuno de 8 horas');

INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 2, 2, 4, TIMESTAMP '2025-11-06 10:30:00', 'PROGRAMADA', 'Control de tiroides');

INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 5, 3, 5, TIMESTAMP '2025-11-07 14:00:00', 'CONFIRMADA', 'Test PCR urgente');

INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 5, 1, 2, TIMESTAMP '2025-11-08 08:30:00', 'PROGRAMADA', 'Perfil bioquímico completo');

INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 2, 4, 1, TIMESTAMP '2025-11-03 11:00:00', 'COMPLETADA', 'Hemograma de control');

INSERT INTO CITAS (ID_CITA, ID_PACIENTE, ID_LABORATORIO, ID_TIPO_ANALISIS, FECHA_CITA, ESTADO, OBSERVACIONES) 
VALUES (SEQ_CITA.NEXTVAL, 5, 2, 4, TIMESTAMP '2025-11-04 09:30:00', 'COMPLETADA', 'Control tiroideo anual');

-- Resultados de Análisis (para citas completadas)
INSERT INTO RESULTADOS_ANALISIS (ID_RESULTADO, ID_CITA, ID_LABORATORISTA, ARCHIVO_PDF, OBSERVACIONES, FECHA_RESULTADO, ESTADO, VALORES_MEDIDOS) 
VALUES (
    SEQ_RESULTADO.NEXTVAL, 
    5, 
    3, 
    '/resultados/2025/11/resultado_cita_5.pdf', 
    'Hemograma dentro de parámetros normales. Glóbulos rojos, blancos y plaquetas en rangos esperados.',
    TIMESTAMP '2025-11-04 15:30:00',
    'COMPLETADO',
    '{"globulos_rojos": "5.2 millones/uL", "globulos_blancos": "7800 /uL", "hemoglobina": "14.5 g/dL", "hematocrito": "43%", "plaquetas": "250000 /uL", "parametros_normales": true}'
);

INSERT INTO RESULTADOS_ANALISIS (ID_RESULTADO, ID_CITA, ID_LABORATORISTA, ARCHIVO_PDF, OBSERVACIONES, FECHA_RESULTADO, ESTADO, VALORES_MEDIDOS) 
VALUES (
    SEQ_RESULTADO.NEXTVAL, 
    6, 
    3, 
    '/resultados/2025/11/resultado_cita_6.pdf', 
    'Perfil tiroideo alterado. TSH elevada, sugiere hipotiroidismo subclínico. Se recomienda consulta con endocrinólogo.',
    TIMESTAMP '2025-11-05 16:45:00',
    'REVISADO',
    '{"TSH": "5.8 mUI/L", "T3_libre": "2.9 pg/mL", "T4_libre": "0.9 ng/dL", "anticuerpos_antiTPO": "45 UI/mL", "rango_TSH_normal": "0.4-4.0 mUI/L", "alerta": "TSH elevada"}'
);

INSERT INTO RESULTADOS_ANALISIS (ID_RESULTADO, ID_CITA, ID_LABORATORISTA, ARCHIVO_PDF, OBSERVACIONES, FECHA_RESULTADO, ESTADO, VALORES_MEDIDOS) 
VALUES (
    SEQ_RESULTADO.NEXTVAL, 
    3, 
    3, 
    NULL, 
    'Resultado PCR COVID-19 en proceso. Se notificará al paciente en las próximas 2 horas.',
    CURRENT_TIMESTAMP,
    'EN_PROCESO',
    '{"test_realizado": "PCR RT", "muestra": "hisopado nasofaringeo", "fecha_toma_muestra": "2025-11-07 14:15:00"}'
);

-- ========================================
-- 7. COMMIT DE CAMBIOS
-- ========================================

COMMIT;

-- ========================================
-- 8. VERIFICACIÓN DE DATOS
-- ========================================

-- Contar registros por tabla
SELECT 'ROLES' AS TABLA, COUNT(*) AS CANTIDAD FROM ROLES
UNION ALL
SELECT 'USUARIOS', COUNT(*) FROM USUARIOS
UNION ALL
SELECT 'LABORATORIOS', COUNT(*) FROM LABORATORIOS
UNION ALL
SELECT 'TIPOS_ANALISIS', COUNT(*) FROM TIPOS_ANALISIS
UNION ALL
SELECT 'LABORATORIO_ANALISIS', COUNT(*) FROM LABORATORIO_ANALISIS
UNION ALL
SELECT 'CITAS', COUNT(*) FROM CITAS
UNION ALL
SELECT 'RESULTADOS_ANALISIS', COUNT(*) FROM RESULTADOS_ANALISIS;

-- Mensaje de éxito
PROMPT ========================================
PROMPT Base de datos inicializada correctamente
PROMPT ========================================
PROMPT Usuario: laboratorio_user
PROMPT Password: Lab2025Pass
PROMPT ========================================

-- Fin del script

